### ISSUE TITLE
Support bean validation

### ISSUE THREAD

**Issue by web-devel** [cuba-labs/cuba-front-generator#34]

**Comment by vyacheslav-pushkin** [comment]
~blocked by https://github.com/cuba-platform/restapi/issues/73~

**Comment by vyacheslav-pushkin** [comment]
Involves changes in:
- front-generator: https://github.com/cuba-platform/front-generator/pull/56
- cuba-react: https://github.com/cuba-platform/cuba-react/pull/29
- cuba-rest-js: https://github.com/cuba-platform/cuba-rest-js/pull/18
- restapi: [PCRAA-CR-8](https://upsource.haulmont.com/platform-cuba-rest-api-add-on/review/PCRAA-CR-8)

**Comment by vyacheslav-pushkin** [comment]
Related issue: https://github.com/cuba-platform/cuba/issues/2541
